version: '2'
services:
  web:
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - OAUTHLIB_INSECURE_TRANSPORT=1
    command: flask run --host=0.0.0.0 --port=8080
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"